<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Olivia Graham</title>

    <!-- Bootstrap core CSS -->
    <link href="assets/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="assets/css/styles.css" rel="stylesheet">

    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="assets/js/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>

<div class="container">

    <div class="row">
        <div class="col-xs-12">
            <div id="header">
                <div id="profile">
                    <img src="assets/img/olivia.jpg" alt="" title="" />
                </div>
                <div id="title">
                    <h1>Olivia Graham</h1>
                </div>
                <div id="navigation">
                    <ul>
                        <li><a href="">About Olivia</a></li>
                        <li><a href="">India</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-xs-12 col-sm-7">
            <div class="section">
                <h2>Summary</h2>
                <p>
                    Software engineer, most recently working for Next Jump Ltd. in London, as part of the Global
                    Expansion team (including work on Next Jump's Global expansion, and key product Reward &amp;
                    Recognition platform).
                </p>
                <p>
                    In September 2015, I am leaving to travel & volunteer in India - I will be returning in November
                    2015. Click here to read more.
                </p>
                <p>
                    Main development experience in web technologies (PHP [Zend Framework], HTML, CSS [CSS, Less & Sass],
                    JavaScript [Prototype & JQuery], Web Services [GO, PHP]).
                </p>
                <p>
                    Graduated from The University of Nottingham in 2013 with a First Class BSc. in Computer Science.
                </p>
                <p>
                    Seven years of programming experience in many languages and technologies (experience from education
                    and free time, around two years professional experience). Two years experience developing with Java
                    and have previously worked with a Java development team at LBi in London (Europe's leading digital
                    marketing agency).
                </p>
            </div>
            <div class="section">
                <h2>Experience</h2>
                <ul class="timeline clearfix">
                    <li>
                        <div class="year float-left">2015</div>
                        <div class="desc float-right">
                            <h3>Next Jump</h3>
                            <h4>Software Engineer June 2013 - Present</h4>
                            <p>Global Product
                                Product development & maintenance (front & back end), project management.

                                Captain of Graduate Recruitment
                                Responsible for organising recruitment events, attendance at University careers fairs, finding & interviewing potential candidates.</p>
                        </div>
                    </li>
                    <li>
                        <div class="year float-left">2013</div>
                        <div class="desc float-right">
                            <h3>Sirosa Technology</h3>
                            <h4>Developer 2012 - May 2013</h4>
                            <p>Part time web-development undertaken during my University course.</p>
                        </div>
                    </li>
                    <li>
                        <div class="year float-left">2012</div>
                        <div class="desc float-right">
                            <h3>Next Jump</h3>
                            <h4>Software Engineer (Intern) June 2011 - June 2012</h4>
                            <p>Web development - html, css, javascript, php, tsql</p>
                        </div>
                    </li>
                    <li>
                        <div class="year float-left">2010</div>
                        <div class="desc float-right">
                            <h3>LBi</h3>
                            <h4>Intern June 2010 - July 2010</h4>
                            <p>Brief summer internship with the Java development team working on BT Tradespace</p>
                        </div>
                    </li>
                </ul>
            </div>
            <div class="section">
                <h2>Education</h2>
                <ul class="timeline clearfix">
                    <li>
                        <div class="year float-left">2009 - 2013</div>
                        <div class="desc float-right">
                            <h3>University of Nottingham</h3>
                            <h4>BSc (Hons) Computer Science 2009 - 2013</h4>
                            <p>Activities: CompSoc - Treasurer in 2nd year, Vice President in 3rd year, Athletics Club, Women's Basketball</p>
                        </div>
                    </li>
                    <li>
                        <div class="year float-left">2007 - 2009</div>
                        <div class="desc float-right">
                            <h3>Strodes College</h3>
                            <h4>A-levels Maths(A), Computing(A), Physics(C) 2007 - 2009</h4>
                            <p>Activities: Hockey, Netball</p>
                        </div>
                    </li>
                    <li>
                        <div class="year float-left">2015</div>
                        <div class="desc float-right">
                            <h3>The Magna Carta School</h3>
                            <h4>8 GCSES at A grade, 1 GCSE at B grade (Religious Studies) 2002 - 2007</h4>
                            <p>Also completed the ICT CiDA Course, obtaining (Credit/Credit).
                                Completed Maths GCSE a year early and went on to do Additional Mathematics (C).

                                Activities: Wide variety of sports including football, rugby, netball and athletics. Also took part in Duke of Edinburgh up to Gold level which included a trip to Morocco with World Challenge in 2006.</p>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
        <div class="col-xs-12 col-sm-5">
            <div class="section">
                <h2>Contact</h2>
                <ul class="contact clearfix">
                    <li>
                        <i class="glyphicon glyphicon-envelope"></i>
                        <span class="contact-item">Email</span>
                    </li>
                    <li>
                        <i class="fa fa-linkedin-square"></i>
                        <span class="contact-item">LinkedIn</span>
                    </li>
                    <li>
                        <i class="fa fa-facebook-square"></i>
                        <span class="contact-item">Facebook</span>
                    </li>
                    <li>
                        <i class="fa fa-twitter"></i>
                        <span class="contact-item">Twitter</span>
                    </li>
                    <li>
                        <i class="fa fa-instagram"></i>
                        <span class="contact-item">Instagram</span>
                    </li>
                    <li>
                        <i class="fa fa-github-alt"></i>
                        <span class="contact-item">Github</span>
                    </li>
                </ul>
            </div>
            <div class="section">
                <h2>Volunteering/Other</h2>
                <ul class="timeline clearfix">
                    <li>
                        <div class="year float-left"></div>
                        <div class="desc float-right">
                            <h3>Code for a Cause</h3>
                            <h4>Next Jump</h4>
                            <p></p>
                        </div>
                    </li>
                    <li>
                        <div class="year float-left"></div>
                        <div class="desc float-right">
                            <h3>Adopt a School</h3>
                            <h4>Next Jump</h4>
                            <p></p>
                        </div>
                    </li>
                    <li>
                        <div class="year float-left"></div>
                        <div class="desc float-right">
                            <h3>Apps for Good</h3>
                            <h4>Expert Volunteer</h4>
                            <p></p>
                        </div>
                    </li>
                </ul>
            </div>
            <div class="section">
                <h2>Skills</h2>
                <ul class="tags clearfix">
                    <li>PHP</li>
                    <li>SQL</li>
                    <li>Java</li>
                </ul>
            </div>
        </div>
    </div>

</div><!-- /.container -->


<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="assets/js/bootstrap.min.js"></script>
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script src="assets/js/ie10-viewport-bug-workaround.js"></script>
</body>
</html>

